HISTORY.md, package.json, src/Panel.jsx, tests/index.js
```rc-collapse-item-active classname``` was not added to the active panel header
=> fix #36 missing rc-collapse-item-active classname on active panel header

README.md, src/Panel.jsx
Hello, I would like to add a 'showArrow' prop to the Panel component to be able to handle the visibility of the small arrow beside the Header. I would like the ability to hide the arrow when passing in my own component as the Header. Please let me know if you have any questions, thanks!
=> Add 'showArrow' prop to Panel to toggle arrow visibility

package.json, src/Collapse.jsx, src/Panel.jsx, src/PanelContent.jsx
Hi.
In React v15.5.0, `React.PropTypes` and `React.createClass` became deprecate.
So I migrated to `prop-types` package and `create-react-class`  package.
=> Fix deprecation warnings for react >= 15.5.0

src/PanelContent.jsx
Make rendering of div element, containeing children dependent on Panel `isActive` flag.
Fixing #43 issue.
=> Remove PanelContent from DOM if it's Panel inactive

README.md
I added `className` to the documentation of the Collapse API since it was suggested in issue #54 after our team assumed that Collapse could not receive this parameter.
=> Add className prop to Collapse API

README.md, src/Collapse.jsx, src/Panel.jsx
I need to add custom styles to the header where I'm using this component, and realised that others may be likely to want to do the same. Therefore, I've added in a new prop, headerClass, to allow users to add customer header styles to this area of the component.
Thanks for creating an awesome component, and please let me know if I've missed anything out! :)
=> Allow user to add custom header classes

src/Panel.jsx
Ref: https://github.com/react-component/collapse/pull/66
=> fix: remove useless space, ref: #66

README.md, src/Panel.jsx, src/PanelContent.jsx, tests/index.spec.js
Resolve https://github.com/ant-design/ant-design/issues/8714
=> Add forceRender attribute to Collapse.Panel

HISTORY.md, package.json, src/Panel.jsx
Preact will ignore the prop which value is boolean false
Convert the value to string can avoid this problem
=> fix(WAI-ARIA): make aria-expanded prop valid in preact

src/PanelContent.jsx
修复 Collapse 在 props 改变时未及时渲染的问题  
Panel 在设置了 forceRender=true 后即使未被展开也应该更新
=> Fix ant-design/ant-design#11279

package.json, src/Collapse.jsx, tests/index.spec.js
Fix https://github.com/ant-design/ant-design/issues/13884
=> Support React Fragment

src/Collapse.jsx
use `this.props.xxx` in `constructor` will lead to a bug in ie9 and ie10.
it is because of inheritance.
If there are no other questions，please merge as soon as possible.
=> fix inherited bug

package.json, src/Collapse.jsx, src/Panel.jsx, src/PanelContent.jsx
Do not bind parameter in render
=> Optimization

README.md, assets/index.less, examples/simple.tsx, src/Collapse.tsx, src/Panel.tsx, src/interface.ts, tests/index.spec.tsx
- Collapse 与 Panel 添加 `collapsible` 属性，取值为 `boolean` 或 `'header'`，默认为 `undefined` 即为 `true`
- `true` 时，Panel 的 header 所有区域均可点击触发展开行为
- `false` 时，相当于给所有的 Panel 子元素设置了 `disabled` 属性，header 区域不可点击，样式与之前的 `disabled` 时相同
- `header` 时，只有点击 Panel 的 header 中的文字区域时才可触发展开行为，点击箭头 icon等不会触发
> 当 Collapse 与 Panel 同时有 `collapsible` 时，优先读取 Panel 的值。
- 删除 2.1.0 中的 `headerCollapsableOnly` 属性
- 删除 Panel 中的 `disabled` 属性，使用 `collapsible=false` 代替
=> chore: support collapsable、 remove disabled of panel and headerCollapsableOnly

README.md, src/Panel.tsx, tests/index.spec.tsx
=> fix: Motion should provider a basic hidden className

README.md, examples/simple.tsx, src/Collapse.tsx, src/Panel.tsx, src/interface.ts, tests/index.spec.tsx
- 3.0.0 中 `collapsible` 属性取值为 `boolean`、`header`，因为之前 @afc163 说的，`false` 和 `disabled` 样式和语义上有所区别，所以这次，把此属性的取值修改为 `header`、`disabled`，去掉了之前的 `boolean`。
这次的改动相对于 3.0.0 来说改动还是比较大，所以大家看看有没有遗漏的地方或者不合适的，还需要确认的是这次的改动是发一下 major 还是 minor 版本。
@zombieJ
=> chore: refactor collapsible value

src/Panel.tsx, tests/index.spec.tsx
close ant-design/ant-design#31039
=> fix: 31039

src/Panel.tsx, tests/index.spec.tsx
header 不是每次都有 holder 对于 flex 布局来说比较麻烦，现在全部包一下样式里就会简单很多。
=> refactor: Wrap all part with element holder

src/Panel.tsx
For accessibility, collapse element should have an aria-disabled attribute
Cases: aria-disabled=
- `true` collapse is disabled
- `false` collapse is not disabled
There are elements that use color as the only visual means to convey state, selection, or other information.
Example:
The "Panel header" accordion is styled to look disabled but it is not conveyed programmatically.
Users who cannot distinguish colors will not have access to the information conveyed by the use of color and may find the page unusable.
learn more - https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-disabled
Reference issue - https://github.com/react-component/collapse/issues/229
Ref: MILL-311
=> Adds "aria-disabled" attribute

package.json, src/Collapse.tsx, src/Panel.tsx, src/PanelContent.tsx, tests/index.spec.tsx
=> refactor: Collapse to function component

src/Collapse.tsx, tests/index.spec.tsx
=> fix: fix CollapsePanel onItemClick not triggering error

src/Panel.tsx, tests/index.spec.tsx
Fixes the headerClass not being applied correctly when passed down. 
fix https://github.com/react-component/collapse/issues/311
=> fix: Correctly applying headerClass to the collapse-header

src/Collapse.tsx, tests/index.spec.tsx
To allow aria-* and data-* attributes we need to pass spread props inside of container as we're doing for other RC components as I see
=> fix: allow data-* and aria-* attributes

.husky/pre-commit, README.md, package.json
更新 husky 用法
README 中的代码块 jsx 修正为 tsx (dumi 编译报错)
=> site: husky update useage, demo jsx to tsx

.dumirc.ts, README.md, now.json
close https://github.com/react-component/collapse/issues/355
=> fix: site build and deploy
