assets/index.less, src/Panel.jsx
=> feat: fix height animate run on safari

README.md
Small grammar changes to the docs.
=> Minor grammar changes

src/Collapse.jsx
via [Conditional <Panel /> makes rc-collapse crash on child.key](https://github.com/react-component/collapse/issues/41)
=> fix: the children of <Collapse /> could be null

README.md
First - great stuff ... find this flexible to work with 👍 .
I was a bit confused but the wording.
Accordion null or false says :activeKey should be an array, a string will work fine. Accordion true says the opposite thinking it should be the same for both cases.
Also moved string in the chart if that is indeed the preferred prop to pass it should show first.
=> Modified accordion notes

README.md, examples/simple.js, src/Collapse.jsx, src/Panel.jsx, src/PanelContent.jsx, tests/index.js
=> feat: add config destroyInactivePanel

README.md, assets/index.less, examples/simple.js, package.json, src/Collapse.jsx, src/Panel.jsx, tests/index.js
close https://github.com/ant-design/ant-design/issues/6119
=> Feature disabled

.gitignore, package.json, src/index.js, tests/index.spec.js
see react-component/react-component.github.io#12
=> feat: add es

HISTORY.md, examples/simple.js, package.json, src/Panel.jsx
=> feat: add prop id for Panel

src/Panel.jsx
=> Add role tablist

assets/index.less
=> style: fix multiline header

README.md, assets/index.less, examples/simple.js, src/Panel.jsx, tests/index.spec.js
for https://github.com/ant-design/ant-design/issues/11626
=> add prop `extra`

src/Collapse.jsx, tests/index.spec.js
close https://github.com/ant-design/ant-design/issues/18166
=> fix: number type activeKeys not working

src/Collapse.jsx, tests/index.spec.js
follow code should not throw:
```jsx
<Collapse defaultKeys={[undefined]}>
<Panel header="title" key="1">
first
</Panel>
</Collapse>
```
=> fix: Not throw if defaultKeys is undefined

assets/index.less, examples/simple.tsx, src/Collapse.tsx, src/Panel.tsx, src/interface.ts, tests/index.spec.tsx
ref: https://github.com/react-component/collapse/pull/164
=> feat: support headerCollapsableOnly

src/Panel.tsx, tests/index.spec.tsx
This reverts commit a9d2a528e1fe6f7e6c0e8d8037f71f99724194f4.
=> Revert "fix: 31039 (#215)"

src/Collapse.tsx, tests/index.spec.tsx
close https://github.com/ant-design/ant-design/issues/36327
close https://github.com/ant-design/ant-design/issues/6179
close https://github.com/react-component/collapse/issues/73#issuecomment-323626120
=> fix: Collapse not working using custom component as panel

src/Panel.tsx, src/interface.ts, tests/index.spec.tsx
Panel container can get event handler like mouseover, mouseleave
=> feat : Panel container get rest props

src/Panel.tsx
https://github.com/ant-design/ant-design/pull/37419#issuecomment-1238812797
https://github.com/ant-design/ant-design/pull/37566
=> fix: Collspse.Panel should not render extra props

src/Collapse.tsx, src/Panel.tsx, tests/index.spec.tsx
**Background**
link: https://github.com/ant-design/ant-design/issues/39628, https://github.com/ant-design/ant-design/pull/39670
=> feat: add forwardRef

src/Panel.tsx, tests/index.spec.tsx
link: https://github.com/ant-design/ant-design/pull/40443/files#r1092692870
=> fix: fix style error

package.json, src/interface.ts
close https://github.com/react-component/collapse/issues/317
ref https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66723
=> type: fix React.Key type error

src/Collapse.tsx
close https://github.com/ant-design/ant-design/issues/46019
=> fix: warning with component name

README.md, assets/index.less, src/Panel.tsx, src/PanelContent.tsx, src/interface.ts, tests/index.spec.tsx, tsconfig.json
support classNames and styles
- ref https://github.com/ant-design/ant-design/pull/49486
=> feat: support classNames and styles
